language: swift
osx_image: xcode10
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
script:
  - pod lib lint
  - xcodebuild -scheme CTDatePicker -workspace CTDatePicker.xcworkspace -sdk iphonesimulator build
